# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('category', models.CharField(choices=[('Space planning and design', 'SPACE PLANNING AND DESIGN'), ('residential', 'RESIDENTIAL'), ('wardrobe and storage units', 'WARDROBE AND STORAGE UNITS'), ('astrology', 'ASTROLOGY'), ('modular kitchen', 'MODULAR KITCHEN'), ('bathroom', 'BATHROOM')], max_length=20)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='query',
            old_name='comment',
            new_name='inquiry',
        ),
    ]
